insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Tea Peppermint', 78.19);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Wine - Pinot Noir Latour', 67.95);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Sauce - Roasted Red Pepper', 16.51);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Yokaline', 56.80);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Tea - Grapefruit Green Tea', 56.01);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Tomatoes - Roma', 27.21);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Tray - 12in Rnd Blk', 62.64);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Carrots - Purple, Organic', 22.56);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Stainless Steel Cleaner Vision', 34.79);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Banana', 25.22);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Wine - Chianti Classica Docg', 58.03);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Sauce - Sesame Thai Dressing', 39.90);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Mousse - Passion Fruit', 13.83);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Icecream Cone - Areo Chocolate', 81.32);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Orange Roughy 4/6 Oz', 44.22);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Salmon - Canned', 82.53);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Tray - 12in Rnd Blk', 54.77);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Wine - Remy Pannier Rose', 85.70);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Skirt - 24 Foot', 46.81);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Cinnamon - Ground', 42.03);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Pork - Bacon Cooked Slcd', 94.69);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Water - Spring 1.5lit', 39.42);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Olives - Morracan Dired', 53.07);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Sunflower Seed Raw', 70.87);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Slt - Individual Portions', 82.29);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Beer - Blue Light', 65.28);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Table Cloth 62x114 Colour', 55.67);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Muffin Hinge 117n', 3.66);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Wine - Ej Gallo Sierra Valley', 86.48);
insert into product (id, name, price) values (NEXTVAL('HIBERNATE_SEQUENCE'), 'Gingerale - Diet - Schweppes', 75.73);